### PR TITLE
Add the patch, options and head method

### PR DESCRIPTION
**Pull request by ValentinH**
Those methods are valid axios method: https://github.com/mzabriskie/axios#axiosheadurl-config

### CODE REVIEW

**Comment by ValentinH** [comment]
Up 🙂

**Comment by ndruwizz** [comment]
Its this fix pushed to NPM? It looks like that version 0.1.0 still using the old pachage

**Comment by ndruwizz** [comment]
@ValentinH Its your fix already publish into NPM?

**Comment by ValentinH** [comment]
I don't  think so because I see we are using our fork 🙂

**Pull request merged**
